name: code_coverage

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop" ]
  workflow_run:
    workflows: [ "build" ]
    types:
      - completed

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  code_coverage:
    needs: code_linting
    runs-on: macos-latest
    steps:
      - name: checkout project sources
        uses: actions/checkout@v3

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: set up jdk 20
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '20'

      - name: create local.properties from secret variables
        run: echo API_KEY=${{ secrets.API_KEY }} > ./local.properties

      - name: setup gradle
        uses: gradle/gradle-build-action@v2

      - name: avd cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: create avd and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          script: echo "generated avd snapshot for caching."

      - name: run ui tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -wipe-data # Emulator options reference: https://developer.android.com/studio/run/emulator-commandline
          disable-animations: true
          script: ./gradlew codeCoverage # Run ui tests: https://developer.android.com/studio/test/command-line#run-tests-build-variants

      - name: archive ui test reports on failure
        uses: actions/upload-artifact@v3
        with:
          name: ui_tests
          path: "**/build/reports/jacoco"